### ISSUE TITLE
使用RabbitMQ自动安装脚本错误

### ISSUE THREAD

**Issue by LiuYinCarl** [Leif160519/centos-script#1]
报错：error: Failed dependencies:
	erlang >= R16B-03 is needed by rabbitmq-server-3.6.6-1.el7.noarch
	systemd is needed by rabbitmq-server-3.6.6-1.el7.noarch
所用系统：Centos6.10/Centos6.8 双机

**Comment by Leif160519** [comment]
你好，可以试着升级erlang版本试试呢，我是在centos 7下安装rabbitmq的，高版本的centos暂时没有尝试，抱歉

**Comment by LiuYinCarl** [comment]
我发现问题可能不只是erlang的版本，rabbitmq和erlang针对centos6和centos7发行的版本是不同的，会用到版本的特有属性。所以我参考了你的代码，修改了部分内容写过了一个脚本，针对6和7下载不同的rabbitmq与erlang。目前在centos6.10和6.8上测试过，可用。centos7未测试，但该部分脚本完全和你的代码一致，应该不会有问题。我稍后提交。

**Comment by LiuYinCarl** [comment]
问题已解决。
