### ISSUE TITLE
翻译一篇关于developertoolset的文章

### ISSUE THREAD

**Issue by LiuYinCarl** [Leif160519/centos-script#3]
你好，最近几天我在安装GCC高版本的时候出现了很多问题，查看国内一些从源码安装的文章，发现几乎所有文章都是过时的。在StackOverflow上寻找相应解决办法的过程中发现了developertoolset（开发者工具集),这一工具解决了我之前关于配置的绝大部分问题。但关于这个工具，中文介绍非常之少，所以我希望翻译这几篇官方引导来提供一个比较好的解决思路，起一个抛砖引玉的作用。但是由于我对这方面知之甚少，不知道这些翻译是否有必要。所以先向你咨询一下。如果你觉得可以的话，我在翻译后将会提交如下内容。

1. [developertoolset的使用引导](https://developers.redhat.com/products/developertoolset/hello-world/#fndtn-rhel-7)
2. SCL管理CentOS软件的一篇介绍文章（通过查阅相关文章进行介绍）
2. 使用SCL安装各版本GCC（G++/python/...）等的一个示范脚本。

**Comment by Leif160519** [comment]
可以啊，支持一波！

**Comment by LiuYinCarl** [comment]
你看下刚才提交的哪有不足，我再改改。如果你感觉这个工具实用性大的话，我有时间的话就充分介绍一下这个工具。再将一些我了解到的常用错误也补充进来。
