### ISSUE TITLE
求大佬微信

### ISSUE THREAD

**Issue by happinesslijian** [Leif160519/centos-script#5]
求大佬微信有个KVM虚拟机的问题 需要请教一下 盼回复

**Comment by Leif160519** [comment]
Kvm我没用过哎，vmware倒比较熟悉

发自我的iPhone

**Comment by happinesslijian** [comment]
> Kvm我没用过哎，vmware倒比较熟悉
> 
> 发自我的iPhone
> 
> > 在 2020年8月27日，17:55，happinesslijian <notifications@github.com> 写道：
> > 
> > ﻿
> > 求大佬微信有个KVM虚拟机的问题 需要请教一下 盼回复
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> 

把你的微信给我就好 感谢🙏

**Comment by Leif160519** [comment]
> > Kvm我没用过哎，vmware倒比较熟悉
> > 
> > 发自我的iPhone
> > 
> > > 在 2020年8月27日，17:55，happinesslijian <notifications@github.com> 写道：
> > > 
> > > ﻿
> > > 求大佬微信有个KVM虚拟机的问题 需要请教一下 盼回复
> > > 
> > > —
> > > You are receiving this because you are subscribed to this thread.
> > > Reply to this email directly, view it on GitHub, or unsubscribe.
> > 
> 
> 把你的微信给我就好 感谢🙏

你想问啥？
